name: Node CI

on: 
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        include:
        - os: windows-latest
          commandPrefix: ''
          electronCacheDir: '$HOME/.electron'
        - os: ubuntu-latest
          commandPrefix: xvfb-run
          electronCacheDir: '~/.cache/electron'
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js 12.x
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - name: Get yarn cache dir
      id: yarn-cache
      run: echo "::set-output name=dir::$(yarn cache dir)"
    - name: Yarn cache
      uses: actions/cache@v1
      with:
        path: ${{ steps.yarn-cache.outputs.dir }}
        key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
        restore-keys: |
          ${{ runner.os }}-yarn-
    - name: Electron cache
      uses: actions/cache@v1
      with:
        path: ${{ matrix.electronCacheDir }}
        key: ${{ runner.os }}-electron-${{ hashFiles('**/yarn.lock') }}
        restore-keys: |
          ${{ runner.os }}-electron-
    - name: yarn install
      run: yarn install
    - name: yarn test
      run: ${{ matrix.commandPrefix }} yarn test --runInBand
      env:
        CI: true
