name: Test

on: 
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js 12.x
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - name: yarn install
      run: |
        yarn install
    - name: yarn test
      if: runner.os != 'Windows'
      run: |
        xvfv-run yarn test --runInBand
    - name: yarn test
      if: runner.os == 'Windows'
      run: |
       yarn test --runInBand
      env:
        CI: true
